const translations = {
  
  "ua": {
    "title": "Каталог AI-Інструментів для Заробітку",
    "earningsBtn": "Дивитись приклади заробітку",
    "compare": "Порівняти",
    "calculator": "💰 Калькулятор прибутку",
    contacts_info: "Якщо у вас є запитання або пропозиції, напишіть нам:",
    telegram: "Телеграм",
    "addTool": "+ Додати свій інструмент",
    "bonus_notion": "Notion AI — +10$ на рахунок",
    "telegram_notify": "🤖 Отримувати сповіщення у Telegram",
    "share_facebook": "Facebook",
    "share_twitter": "Twitter",
    "share_telegram": "Telegram",
    "share_linkedin": "LinkedIn",
    "subscribe_title": "📬 Підписка на нові AI-інструменти",
    "subscribe_desc": "Отримуйте оновлення про нові інструменти, можливості та поради для заробітку прямо на e-mail або в Telegram",
    "subscribe_btn": "🔔 Підписатися на email-дайджест",
    "subscribe_thanks": "✅ Дякуємо! Ви підписані.",
    "share_section_title": "🔗 Поділитися сайтом",
    "bonus_upwork": "Upwork — $0 комісії перші 30 днів",
    "bonus_fiverr": "Fiverr — $100 бонусу",
    "support_thanks": "Дякуємо за підтримку 💙",
    "about_title": "Про нас",
    contacts_header: "Зв'яжіться з нами",
    "about_desc": "Ми — команда ентузіастів, яка створила цей каталог...",
    contacts_title: "Контакти",
    "contacts_desc": "Маєш питання, ідеї або хочеш запропонувати новий інструмент? Напиши нам!",
    "email_label": "Email:",
    "about_intro_1": "Я, Артем, створив <strong>Каталог AI-інструментів</strong>, щоб допомогти усім знайти найкращі способи заробітку з AI.",
"about_intro_2": "Моя мета — зробити технології доступними для всіх. Тут ви знайдете реальні кейси, поради, і рейтинги, щоб почати з нуля.",
"about_intro_3": "Проєкт створено з ❤️ у 2025 році.",

    "telegram_label": "Telegram:",
    "label_earnings": "Заробіток",
"label_jobs": "Вакансій",
"label_investment": "Вкладення",
"key_пошук_інструменту": "Пошук інструменту...",
"key_усі_категорії": "Усі категорії",
"key_текст": "Текст",
"key_зображення": "Зображення",
"key_відео": "Відео",
"key_голос": "Голос",
"nav_home": "Головна",
"nav_about": "Про нас",
"nav_contacts": "Контакти",
"nav_support": "☕ Підтримати проєкт",

"key_сайт": "Сайт",
"key_логотип": "Логотип",
"key_організація": "Організація",
"key_усі_рівні": "Усі рівні",
"key_для_новачків": "Для новачків",
"key_середній_рівень": "Середній рівень",
"key_для_просунутих": "Для просунутих",
"key_сортування": "Сортування",
"key_спочатку_нові": "Спочатку нові",
"key_спочатку_популярні": "Спочатку популярні",

"key_дані_приблизні": "📊 Дані приблизні — базуються на середній статистиці ринку, фріланс-платформ і відкритих джерел.",
"key_заробіток_і_вакансії": "Заробіток і вакансії можуть відрізнятись залежно від навичок і часу.",
"key_опис_chatgpt": "Генерує тексти, відповіді, ідеї. Використовуй для написання статей, постів або фрілансу.",
"key_відкрити": "Відкрити",
"key_порівняти": "🧩 Порівняти",

"key_опис_midjourney": "Створення зображень на основі тексту. Ідеально підходить для дизайну, NFT, Pinterest.",
"key_опис_elevenlabs": "AI-голосове озвучення. Можна створювати TikTok, відео або продавати озвучки клієнтам.",
"key_опис_durable": "AI-конструктор сайтів. Створює сайти за 30 секунд, корисно для фрілансерів та бізнесу.",
"key_опис_looka": "AI-генератор логотипів. Допомагає створювати бренд швидко і просто, навіть без дизайнера.",
"key_опис_notion": "Асистент для планування, написання текстів, організації — підходить для навчання і бізнесу.",
"key_опис_runway": "Відеоредактор на основі AI. Можна створювати відео без досвіду, ідеально для TikTok/YouTube.",
"key_відкрити": "Відкрити",
"key_порівняти": "🧩 Порівняти",
consulting_help: "💼 Потрібна допомога з AI-інструментами або запуском сайту?",
    consulting_button: "✉️ Напиши на сервері в Telegram, я відпишу тобі.",
contacts_titlee: "← Назад до головної",
    coming_soonn: "Скоро буде",
    coming_soon: "🚧 Розділ скоро буде! 🚧",
    coming_soon_desc: "Ми працюємо над цією сторінкою. Незабаром тут з’явиться корисна інформація.",
"key_підтримай": "💸 Підтримай проєкт",
"key_отримай_бонуси": "отримай бонуси за реєстрацію",

"subscribe_pitch_1": "🔐 Хочеш більше реальних AI-кейсів і прибуткових стратегій?",
"subscribe_pitch_2": "📩 Підпишись на наш закритий дайджест — лише $1/тиждень",
"subscribe_button": "🔔 Підписатися",

"key_приклади_заробітку": "Приклади заробітку",
"key_earn_midjourney": "Midjourney: $380 на Etsy (арт-постери)",
"key_earn_durable": "Durable: 5 сайтів × $8 = $40",
"key_earn_elevenlabs": "ElevenLabs: $200 за озвучення TikTok",
"key_earn_notion": "Notion AI: $35 за реферати",
"key_порівняння_інструментів": "Порівняння AI-Інструментів",

"key_мінікурси_заголовок": "Міні-курси та корисні гайди",
"key_заробіток_ai": "Як почати заробляти з AI?",
"key_відео_гайд": "Відео-гайд (1 хв) або текстова інструкція",
"key_топ_5_ai": "ТОП 5 способів заробітку з AI для новачка",
"key_читати": "читати",
"key_ai_шахрайство": "Як не попастися на шахрайство при роботі з AI?",
"key_faq": "FAQ",
"key_перший_клієнт": "Перший продаж фрілансеру: як знайти клієнта?",
"key_короткий_курс": "Короткий курс",
"key_старт_без_знань": "Старт без знань: Як зробити простий сайт/логотип за 5 хвилин?",
"key_відео": "Відео",
"key_продаж_ai": "Як продати AI-роботу на Etsy/Pinterest?",
"key_faq_заголовок": "📚 Поширені питання (FAQ)",
"key_faq_опис": "Швидкі відповіді на найпопулярніші запити",
"key_faq_q1": "Як заробити на AI для тексту?",
"key_faq_a1": "Використовуй ChatGPT або Notion AI для написання статей, SEO-контенту, описів товарів і фрілансу на платформах.",
"key_faq_q2": "Які ризики для авторських прав при генерації тексту?",
"key_faq_a2": "Не копіюй чужі фрази дослівно. Генеруй унікальні тексти, додавай редагування й перевірку через антиплагіат.",
"key_faq_q3": "Як монетизувати AI-зображення?",
"key_faq_a3": "Генеруй арт через Midjourney або Leonardo.ai і продавай на Etsy, Redbubble або як постери в Instagram.",
"key_faq_q4": "Чи реально заробити на AI-відео новачку?",
"key_faq_a4": "Так! Створи озвучку через ElevenLabs або відео через Runway, додай текст і музику — і заливай у TikTok або Shorts.",
"key_faq_q5": "Як уникати бану відео з AI-озвучкою?",
"key_faq_a5": "Додавай коментар або контекст, уникай політичних/чутливих тем, змінюй голос або міксуй з природним.",
"top_users": "🏆 Топ користувачів",
"key_інструмент": "Інструмент:",
"key_платформа": "Платформа:",
"key_годин_тиждень": "Годин/замовлень на тиждень:",
"key_розрахувати": "📈 Розрахувати",
"community_heading": "🤝 Запитати у спільноти",
"community_description": "Маєш питання або хочеш поділитись досвідом? Приєднуйся до нашої Telegram-групи та спілкуйся з іншими користувачами!",
"join_telegram": "🔗 Приєднатися до Telegram",
"badge_top_earnings": "🔥 Топ заробіток",
"badge_no_investment": "💸 Без вкладень",
"badge_many_jobs": "💼 Багато вакансій",
"modal_add_tool_title": "Додати AI-Інструмент",
"label_tool_name": "Назва інструменту:",
"label_category": "Категорія:",
"label_username": "Ваш нікнейм:",
"label_link": "Посилання:",
"label_description": "Опис:",
"label_honeypot": "Якщо ви людина — залиште це поле порожнім:",
"button_submit": "Надіслати",
"button_clear_form": "Очистити форму",
email_placeholder: "Ваш e-mail",
compare_alert: "Виберіть щонайменше 2 інструменти для порівняння.",
      field_parameter: "Параметр",
      field_name: "Назва",
      field_price: "Ціна",
      field_features: "Функції",
      field_difficulty: "Легкість",
      field_language: "Мова",
      field_payout: "Заробіток",
      field_popularity: "Популярність",
      calc_platform: "Платформа",
      calc_profit_after_fee: "Прибуток після комісії",
      calc_week: "за тиждень",
      calc_month: "за місяць",
      calc_rate: "Ставка",
      calc_fee: "Комісія",
      nav_add_history: "Історії",

    "chatgpt_title": "ChatGPT — AI-Інструмент",
"chatgpt_tip": "Порада:",
"chatgpt_tip_text": "Використовуй ChatGPT для створення портфоліо, резюме, блогів або написання SEO-контенту для клієнтів на Upwork або Fiverr.",
"show_example": "Показати приклад заробітку",
"example_title": "📌 Як саме заробити з ChatGPT?",
"example_guide": "Короткий гайд:",
"example_step1": "Зареєструйся на Fiverr або Upwork.",
"example_step2": "Створи профіль і запропонуй послуги написання текстів.",
"example_step3": "Генеруй тексти через ChatGPT, покращуй і надсилай клієнтам.",
"example_step4": "Стартова ціна: $10 за 500 слів.",
"example_case": "Кейс: Андрій, 24 роки, Київ — за 2 місяці заробив $1200. Перший місяць: $400, другий: $800.",
"example_tool": "Інструмент: Безкоштовна версія доступна, Pro — $20/місяць.",
"chatgpt_description": "ChatGPT — це один з найпотужніших текстових генераторів, який може писати статті, листи, сценарії, код та багато іншого. Ідеально підходить для копірайтингу, навчання, створення резюме, постів у соцмережах або SEO-контенту. Може значно пришвидшити роботу фрілансера або допомогти студенту.",
"category_text": "Текст",
"login": "Увійти",
"login_title": "Вхід у профіль",
"login_header": "Вхід",
"login_btn": "Увійти",
"email": "Email",
"password": "Пароль",
"profile_title": "Мій профіль",
"profile_welcome": "Вітаємо у профілі!",
"logout": "Вийти",


label_name: "Ім'я:",
  label_message: "Повідомлення:",
  send_btn: "Надіслати",
contact_title: "Контакти — Каталог AI-Інструментів",
    contact_description: "Зв’яжись з нами, якщо маєш питання або хочеш запропонувати інструмент.",
    contact_back: "← Назад до головної",
    contact_heading: "Контакти",
    contact_text: "💬 Пропозиції, запитання та співпраця — раді відповісти!",

no_votes: "Ще немає голосів",
"rating_summary": "({votes} votes, average: {avg})",
"back_to_catalog": "Назад до каталогу",

rating_summary: "({votes} голосів, середня: {avg})",
    no_votes: "Ще немає голосів",
    midjourney_title: "Midjourney",
    midjourney_tip: "Порада:",
    midjourney_tip_text: "Генеруй картинки для Pinterest, Etsy або соцмереж.",
    show_example: "Показати приклад заробітку",
    example_title: "📌 Як саме заробити з Midjourney?",
    example_guide: "Короткий гайд:",
    midjourney_step1: "Створи акаунт на Midjourney через Discord.",
    midjourney_step2: "Генеруй зображення за запитами — арт, постери, продукти.",
    midjourney_step3: "Викладай їх на Etsy, Redbubble або продавай як кастомні замовлення.",
    midjourney_step4: "Додатково — продавай через Telegram або Fiverr.",
    midjourney_case: "Кейс: Катя, 20 років, Львів — генерує арт-постери для Etsy та Instagram. За місяць заробила $380, зокрема через 6 замовлень на Pinterest-оформлення.",
    example_tool: "Інструмент: Платна підписка від $10/місяць. Можна почати з безкоштовного пробного періоду.",
    key_опис_leonardo: "Генератор зображень для коміксів, ігор, арту. Добре працює з концепт-дизайном та NFT.",
    key_опис_poe: "Чат-платформа, де можна взаємодіяти з ChatGPT, Claude та іншими ботами одночасно.",
    key_опис_heygen: "Генерує відео з аватарами та озвучкою. Корисно для презентацій, курсів і соціальних мереж.",
    key_опис_copyai: "Створює маркетингові тексти, email-листи, SEO-описи — ідеально для копірайтерів.",
    key_опис_bluewillow: "AI-генерація зображень у стилі Midjourney. Можна використовувати для дизайну, принтів і NFT.", 
    key_опис_voicemod: "Голосовий модифікатор у реальному часі. Корисно для стрімерів, відео або розваг.",
    key_опис_writesonic: "Генерує SEO-тексти, блоги, email-кампанії. Добре працює для маркетологів і копірайтерів.",
    key_опис_artbreeder: "AI-злиття зображень та створення облич. Ідеально для арт-дизайну, портретів та творчості.",
    key_опис_speechify: "Перетворює текст у природну мову. Ідеально для прослуховування статей, книг або PDF.",
    key_опис_quillbot: "Перефразовує тексти, спрощує граматику. Дуже корисно для студентів та SEO-редакторів.",
    key_опис_canva: "Додає AI-функції до Canva: автодизайн, генерація зображень, шаблони — все в одному.",
    key_опис_taskade: "AI для створення чеклістів, нотаток і робочих просторів — підходить для команд і студентів.",
    key_опис_teleport: "Генерує повні HTML-сайти з простого опису. Корисно для швидкого старту фріланс-проектів.",
    key_опис_lumen5: "Створює відео з тексту автоматично. Добре підходить для соцмереж, презентацій, реклами.",
    key_опис_jenni: "Помічник для академічного письма. Пропонує фрази, формулювання, підказки — ідеально для студентів.",
    key_заголовок_кейсів: "💡 Історії Заробітку з AI",
    key_кейс_molly: "👩‍🏫 <strong>Molly (США)</strong> заробляє <strong>$100,000+/міс</strong><br>Створює онлайн-курси з допомогою <strong>ChatGPT</strong> і <strong>Notion AI</strong>.<br><a href='https://www.youtube.com/@MollyKeyser' class='earnings-btn' target='_blank' style='margin-top:10px; display:inline-block;'>🔗 Дивитись кейс</a>",
    key_кейс_jason: "👨‍💼 <strong>Jason Lee</strong> (157 K підписників) ділиться AI-стратегіями для пасивного доходу,<br>заявляючи до <strong>$1,046/день</strong> через AI‑дропшипінг, POD та афіліат-маркетинг.<br><a href='https://www.youtube.com/@jasonleefinance' class='earnings-btn' target='_blank' style='margin-top:10px; display:inline-block;'>🔗 Дивитись кейс</a>",
    key_кейс_amanda: "👩‍💻 <strong>Amanda (США)</strong> заробляє до $8,000 за 3 тижні, тестуючи чат‑ботів вночі.",
    key_кейс_iryna: "👩‍🎨 <strong>Ірина</strong> створює ілюстрації в Midjourney та продає цифрові постери на Etsy — $370/місяць.",
    key_кейс_taras: "💬 <strong>Тарас</strong> використовує ChatGPT для написання текстів на Fiverr — $25–50 за замовлення.",
    key_кейс_leila: "🎥 <strong>Лейла</strong> публікує короткі відео про AI у TikTok і заробляє на партнерках — $800/місяць.",
    key_кейс_ben: "🧠 <strong>Ben</strong> створив 2 AI‑інфлюенсери й заробив $250,000 за рік на маркетингу.",
    "chatgpt_slide_1": "🎯 \"Створив лендінг за 30 хв через ChatGPT\" — фрилансер з Польщі",
"chatgpt_slide_2": "💬 \"Пишу email-розсилки клієнтам через AI\" — контентник з Канади",
"chatgpt_slide_3": "📖 \"Продала 50+ текстів на Fiverr за місяць\" — копірайтер з Одеси",

"tab_features": "🔧 Функції",
"tab_tips": "💡 Поради",
"tab_examples": "📚 Приклади",
    
"nav_home": "🏠 Головна",
"nav_compare": "📊 Порівняння",
"nav_calculator": "🧮 Калькулятор",
"nav_add_tool": "➕ Додати",
form_title: "📨 Додати свою історію",
    form_name: "Ім'я",
    form_country: "Країна",
    form_age: "Вік",
    form_text: "Як ти заробляєш з AI?",
    form_earnings: "Прибуток ($)",
    form_submit: "Зберегти",
    form_cancel: "Закрити"


  },
  "en": {
    "title": "AI Tools Catalog for Earning",
    "earningsBtn": "View earning examples",
    "compare": "Compare",
    "calculator": "💰 Earnings Calculator",
    "addTool": "+ Submit your tool",
    "bonus_notion": "Notion AI — $10 credit",
    "telegram_notify": "🤖 Get updates via Telegram",
    "share_facebook": "Facebook",
    "share_twitter": "Twitter",
    "share_telegram": "Telegram",
    "share_linkedin": "LinkedIn",
    "subscribe_title": "📬 Subscribe to new AI tools",
    "subscribe_desc": "Get updates about new tools, earning tips and features via email or Telegram",
    "subscribe_btn": "🔔 Subscribe to email digest",
    "subscribe_thanks": "✅ Thank you! You're subscribed.",
    "share_section_title": "🔗 Share the site",
    "bonus_upwork": "Upwork — $0 fees for 30 days",
    "bonus_fiverr": "Fiverr — $100 bonus",
    "support_thanks": "Thanks for your support 💙",
    "about_title": "About Us",
    "about_desc": "We are a team of enthusiasts who created this catalog...",
    contacts_title: "Contacts",
    "contacts_desc": "Have questions or ideas? Want to suggest a new tool? Write to us!",
    "email_label": "Email:",
    "telegram_label": "Telegram:",
    contacts_header: "Contact Us",
    "key_пошук_інструменту": "Search tool...",
"key_усі_категорії": "All categories",
"key_текст": "Text",
"key_зображення": "Image",
"key_відео": "Video",
"key_голос": "Voice",
"key_сайт": "Website",
"key_логотип": "Logo",
"about_intro_1": "I, Artem, created the <strong>AI Tools Catalog</strong> to help everyone find the best ways to earn with AI.",
"about_intro_2": "My goal is to make technology accessible to everyone. Here you’ll find real success stories, tips, and ratings to get started from scratch.",
"about_intro_3": "Project made with ❤️ in 2025.",
"key_організація": "Organization",
"key_усі_рівні": "All levels",
"key_для_новачків": "Beginner",
"key_середній_рівень": "Intermediate",
"key_для_просунутих": "Advanced",
"key_сортування": "Sort by",
"key_спочатку_нові": "Newest first",
"key_спочатку_популярні": "Most popular",
nav_add_history: "Stories",
"key_дані_приблизні": "📊 Data is approximate — based on average market stats, freelance platforms, and public sources.",
"key_заробіток_і_вакансії": "Earnings and job offers may vary depending on your skills and time.",
"key_опис_chatgpt": "Generates texts, replies, and ideas. Use it for writing articles, posts, or freelancing.",
"key_відкрити": "Open",
"key_порівняти": "🧩 Compare",
"key_опис_midjourney": "Create images from text. Perfect for design, NFTs, and Pinterest.",
"key_опис_elevenlabs": "AI voice dubbing. Great for TikTok, video production or client work.",
"key_опис_durable": "AI site builder. Create websites in 30 seconds, ideal for freelancers and businesses.",
"key_опис_looka": "AI logo generator. Helps create a brand quickly and easily, even without a designer.",
"key_опис_notion": "Assistant for planning, writing and organizing — suitable for study and business.",
"key_опис_runway": "AI-based video editor. Easy content creation for TikTok/YouTube without experience.",
"key_відкрити": "Open",
"key_порівняти": "🧩 Compare",

contacts_titlee: "← Back to homepage",
    coming_soonn: "Coming soon",
    coming_soon: "🚧 Section coming soon! 🚧",
    coming_soon_desc: "We're working on this page. Useful information will appear here soon.",
"key_підтримай": "💸 Support the project",
"key_отримай_бонуси": "get bonuses for signing up",

"key_приклади_заробітку": "Earning Examples",
"key_earn_midjourney": "Midjourney: $380 on Etsy (art posters)",
"key_earn_durable": "Durable: 5 sites × $8 = $40",
"key_earn_elevenlabs": "ElevenLabs: $200 for TikTok voice-over",
"key_earn_notion": "Notion AI: $35 for essays",
"key_порівняння_інструментів": "AI Tools Comparison",

"key_мінікурси_заголовок": "Mini-courses and useful guides",
"key_заробіток_ai": "How to start earning with AI?",
"key_відео_гайд": "Video guide (1 min) or text instructions",
"key_топ_5_ai": "Top 5 AI earning methods for beginners",
"key_читати": "read",
"key_ai_шахрайство": "How to avoid scams while working with AI?",
"key_faq": "FAQ",
"key_перший_клієнт": "First freelance sale: how to find a client?",
"key_короткий_курс": "Short course",
"key_старт_без_знань": "Start without knowledge: make a site/logo in 5 minutes",
"key_відео": "Video",
"key_продаж_ai": "How to sell AI work on Etsy/Pinterest?",
"key_faq_заголовок": "📚 Frequently Asked Questions (FAQ)",
"key_faq_опис": "Quick answers to the most common questions",
"key_faq_q1": "How to earn using AI for text?",
"key_faq_a1": "Use ChatGPT or Notion AI to write articles, SEO content, product descriptions, and freelance gigs.",
"key_faq_q2": "What are the copyright risks with AI text generation?",
"key_faq_a2": "Don’t copy phrases word-for-word. Generate unique text and use plagiarism checkers.",
"key_faq_q3": "How to monetize AI-generated images?",
"key_faq_a3": "Generate art with Midjourney or Leonardo.ai and sell on Etsy, Redbubble, or as posters on Instagram.",
"key_faq_q4": "Can beginners make money with AI video?",
"key_faq_a4": "Yes! Use ElevenLabs for voiceovers or Runway for video creation, then upload to TikTok or Shorts.",
"key_faq_q5": "How to avoid bans on AI-voiced videos?",
"key_faq_a5": "Add context/commentary, avoid political or sensitive content, modify or mix the voice.",
"top_users": "🏆 Top Users",
"key_інструмент": "Tool:",
"key_платформа": "Platform:",
"key_годин_тиждень": "Hours/orders per week:",
"key_розрахувати": "📈 Calculate",
"community_heading": "🤝 Ask the Community",
"community_description": "Have a question or want to share your experience? Join our Telegram group and chat with other users!",
"join_telegram": "🔗 Join Telegram",
"label_earnings": "Earnings",
"label_jobs": "Jobs",
"label_investment": "Investment",
"badge_top_earnings": "🔥 Top Earnings",
"badge_no_investment": "💸 No Investment",
"badge_many_jobs": "💼 Many Jobs",
"modal_add_tool_title": "Add AI Tool",
"label_tool_name": "Tool Name:",
"label_category": "Category:",
contacts_info: "If you have any questions or suggestions, write to us:",
    telegram: "Telegram",
"label_username": "Your Nickname:",
"label_link": "Link:",
"label_description": "Description:",
"label_honeypot": "If you're human — leave this field empty:",
"button_submit": "Submit",
"button_clear_form": "Clear Form",
email_placeholder: "Your email",

"chatgpt_title": "ChatGPT — AI Tool",
"chatgpt_tip": "Tip:",
"chatgpt_tip_text": "Use ChatGPT to create a portfolio, resume, blogs, or write SEO content for clients on Upwork or Fiverr.",
"show_example": "Show earning example",
"example_title": "📌 How exactly to earn with ChatGPT?",
"example_guide": "Quick guide:",
"example_step1": "Sign up on Fiverr or Upwork.",
"example_step2": "Create a profile and offer writing services.",
"example_step3": "Generate texts via ChatGPT, improve and send to clients.",
"example_step4": "Starting price: $10 for 500 words.",
"example_case": "Case: Andrew, 24, from New York — earned $1200 in 2 months. First month: $400, second month: $800.",
"example_tool": "Tool: Free version available, Pro — $20/month.",
"chatgpt_description": "ChatGPT is one of the most powerful text generators capable of writing articles, emails, scripts, code, and much more. It’s ideal for copywriting, learning, building resumes, social media posts, or SEO content. It can significantly speed up a freelancer’s workflow or help a student.",
"category_text": "Text",
no_votes: "No votes yet",
"rating_summary": "({votes} votes, average: {avg})",
"back_to_catalog": "Back to catalog",
rating_summary: "({votes} votes, average: {avg})",
no_votes: "No votes yet",
midjourney_title: "Midjourney",
midjourney_tip: "Tip:",
midjourney_tip_text: "Generate images for Pinterest, Etsy, or social media.",
show_example: "Show earning example",
example_title: "📌 How to earn with Midjourney?",
example_guide: "Quick guide:",
midjourney_step1: "Create an account on Midjourney via Discord.",
midjourney_step2: "Generate images for art, posters, products.",
midjourney_step3: "Upload them on Etsy, Redbubble, or sell as custom orders.",
midjourney_step4: "Additionally — sell through Telegram or Fiverr.",
midjourney_case: "Case: Kate, 20, from Lviv — creates art posters for Etsy and Instagram. Earned $380 in a month, including 6 Pinterest design orders.",
example_tool: "Tool: Paid subscription from $10/month. Free trial available.",
"coming-soon": "coming-soon",
"coming-desc": "coming-soon",
"login": "Login",
"login_title": "Login to Profile",
"login_header": "Login",
"login_btn": "Login",
"nav_home": "Home",
"nav_about": "About Us",
"nav_contacts": "Contacts",
"nav_support": "☕ Support the Project",

"subscribe_pitch_1": "🔐 Want more real AI case studies and profitable strategies?",
"subscribe_pitch_2": "📩 Subscribe to our exclusive digest — only $1/week",
"subscribe_button": "🔔 Subscribe",

key_опис_leonardo: "Image generator for comics, games, and art. Great for concept design and NFT work.",
key_опис_poe: "Chat platform to interact with ChatGPT, Claude, and other bots all in one place.",
key_опис_poe: "Chat-Plattform zur Interaktion mit ChatGPT, Claude und anderen Bots an einem Ort.",
key_опис_heygen: "Generates avatar videos with voice. Useful for presentations, courses, and social media.",
key_опис_copyai: "Creates marketing texts, emails, SEO descriptions — ideal for copywriters.",
key_опис_bluewillow: "AI image generation like Midjourney. Great for design, prints, and NFTs.",
key_опис_voicemod: "Real-time voice changer. Useful for streamers, video creators, or fun.",
key_опис_writesonic: "Generates SEO texts, blog posts, and email campaigns. Great for marketers and copywriters.",
    key_опис_artbreeder: "AI image blending and face creation. Ideal for art design, portraits, and creativity.",
    label_name: "Name:",
    label_message: "Message:",
    send_btn: "Send",
    key_опис_speechify: "Turns text into natural speech. Ideal for listening to articles, books, or PDFs.",
    key_опис_quillbot: "Paraphrases text, improves grammar. Very useful for students and SEO editors.",
    key_опис_canva: "Adds AI tools to Canva: auto design, image generation, templates — all in one.",
    key_опис_taskade: "AI for creating checklists, notes, workspaces — good for teams and students.",
    key_опис_teleport: "Generates full HTML websites from a simple description. Useful for fast freelance start.",
    key_опис_lumen5: "Turns text into videos automatically. Great for social media, presentations, ads.",
    key_опис_jenni: "Academic writing assistant. Suggests phrases and wording — perfect for students.",
    key_заголовок_кейсів: "💡 AI Earning Stories",
    key_кейс_molly: "👩‍🏫 <strong>Molly (USA)</strong> earns <strong>$100,000+/month</strong><br>Creates online courses using <strong>ChatGPT</strong> and <strong>Notion AI</strong>.<br><a href='https://www.youtube.com/@MollyKeyser' class='earnings-btn' target='_blank' style='margin-top:10px; display:inline-block;'>🔗 Watch Case</a>",
 key_кейс_jason: "👨‍💼 <strong>Jason Lee</strong> (157 K subs) shares AI strategies for passive income,<br>claiming up to <strong>$1,046/day</strong> via AI dropshipping, POD & affiliate marketing.<br><a href='https://www.youtube.com/@jasonleefinance' class='earnings-btn' target='_blank' style='margin-top:10px; display:inline-block;'>🔗 Watch case</a>",
key_кейс_amanda: "👩‍💻 <strong>Amanda (USA)</strong> earns up to $8,000 in 3 weeks testing AI chatbots during night shifts.",
key_кейс_iryna: "👩‍🎨 <strong>Iryna</strong> creates illustrations in Midjourney and sells digital posters on Etsy — $370/month.",
key_кейс_taras: "💬 <strong>Taras</strong> uses ChatGPT to write texts on Fiverr — $25–50 per order.",
key_кейс_leila: "🎥 <strong>Leila</strong> posts short videos about AI on TikTok and earns through affiliate links — $800/month.",
key_кейс_ben: "🧠 <strong>Ben</strong> built 2 AI influencers and earned $250,000 in one year from marketing.",
"chatgpt_slide_1": "🎯 \"Created a landing page in 30 min using ChatGPT\" — freelancer from Poland",
"chatgpt_slide_2": "💬 \"I write email campaigns for clients using AI\" — content creator from Canada",
"chatgpt_slide_3": "📖 \"Sold 50+ texts on Fiverr in a month\" — copywriter from Odesa",

"tab_features": "🔧 Features",
"tab_tips": "💡 Tips",
"tab_examples": "📚 Examples",
"nav_home": "🏠 Home",
"nav_compare": "📊 Compare",
"nav_calculator": "🧮 Calculator",
"nav_add_tool": "➕ Add",
form_title: "📨 Add your story",
    form_name: "Name",
    form_country: "Country",
    form_age: "Age",
    form_text: "How are you earning with AI?",
    form_earnings: "Earnings ($)",
    form_submit: "Submit",
    form_cancel: "Cancel",

    contact_title: "Contact — AI Tools Catalog",
    contact_description: "Get in touch with us if you have questions or want to suggest a tool.",
    contact_back: "← Back to homepage",
    contact_heading: "Contact",
    contact_text: "💬 Suggestions, questions, or partnerships — we're happy to hear from you!",
consulting_help: "💼 Need help with AI tools or launching a website?",
    consulting_button: "✉️ Message me on the Telegram server and I’ll reply."




  },




  "de": {
    "title": "KI-Tools-Katalog zum Geldverdienen",
    "earningsBtn": "Beispiele für Einnahmen ansehen",
    "compare": "Vergleichen",
    "calculator": "💰 Gewinnrechner",
    "addTool": "+ Eigenes Tool hinzufügen",
    "bonus_notion": "Notion AI — 10€ Guthaben",
    "telegram_notify": "🤖 Updates über Telegram erhalten",
    "share_facebook": "Facebook",
    "share_twitter": "Twitter",
    "share_telegram": "Telegram",
    "share_linkedin": "LinkedIn",
    "subscribe_title": "📬 Neue KI-Tools abonnieren",
    "subscribe_desc": "Erhalte Updates zu neuen Tools, Verdienstmöglichkeiten und Tipps per E-Mail oder Telegram",
    "subscribe_btn": "🔔 E-Mail-Newsletter abonnieren",
    "subscribe_thanks": "✅ Danke! Du bist jetzt abonniert.",
    "share_section_title": "🔗 Webseite teilen",
    "bonus_upwork": "Upwork — 0% Gebühren für 30 Tage",
    "bonus_fiverr": "Fiverr — 100€ Bonus",
    "support_thanks": "Danke für deine Unterstützung 💙",
    "about_title": "Über uns",
    "about_desc": "Wir sind ein Team von Enthusiasten, das diesen Katalog erstellt hat...",
    contacts_title: "Kontakte",
    "contacts_desc": "Hast du Fragen, Ideen oder möchtest ein neues Tool vorschlagen? Schreib uns!",
    "email_label": "E-Mail:",
    "telegram_label": "Telegram:",

    "key_пошук_інструменту": "Werkzeug suchen...",
"key_усі_категорії": "Alle Kategorien",
"key_текст": "Text",
"key_зображення": "Bild",
"key_відео": "Video",
"key_голос": "Stimme",
"key_сайт": "Webseite",
"key_логотип": "Logo",
"key_організація": "Organisation",
"key_усі_рівні": "Alle Niveaus",
"key_для_новачків": "Anfänger",
"key_середній_рівень": "Mittelstufe",
"key_для_просунутих": "Fortgeschritten",
"key_сортування": "Sortierung",
"key_спочатку_нові": "Neueste zuerst",
"key_спочатку_популярні": "Beliebteste zuerst",

"key_дані_приблизні": "📊 Daten sind ungefähre Angaben — basierend auf durchschnittlichen Marktwerten, Freelance-Plattformen und öffentlichen Quellen.",
"key_заробіток_і_вакансії": "Einnahmen und Jobs können je nach Fähigkeiten und Zeitaufwand variieren.",
"key_опис_chatgpt": "Erzeugt Texte, Antworten und Ideen. Nutze es für Artikel, Beiträge oder Freelancing.",
"key_відкрити": "Öffnen",
"key_порівняти": "🧩 Vergleichen",

"key_опис_midjourney": "Erstellt Bilder aus Text. Ideal für Design, NFTs und Pinterest.",
"key_опис_elevenlabs": "KI-Stimmenvertonung. Perfekt für TikTok, Videos oder Kundenprojekte.",
"key_опис_durable": "KI-Website-Builder. Erstellt Websites in 30 Sekunden – ideal für Freelancer und Unternehmen.",
"key_опис_looka": "KI-Logo-Generator. Erleichtert schnelles Branding – auch ohne Designer.",
"key_опис_notion": "Assistent für Planung, Schreiben und Organisation — ideal für Studium und Business.",
"key_опис_runway": "KI-Videobearbeiter. Einfach Videos für TikTok/YouTube erstellen – ohne Erfahrung.",
"key_відкрити": "Öffnen",
"key_порівняти": "🧩 Vergleichen",

"key_підтримай": "💸 Unterstütze das Projekt",
"key_отримай_бонуси": "erhalte Boni für die Anmeldung",

"key_приклади_заробітку": "Verdienstbeispiele",
"key_earn_midjourney": "Midjourney: 380 $ auf Etsy (Kunstdrucke)",
"key_earn_durable": "Durable: 5 Websites × 8 $ = 40 $",
"key_earn_elevenlabs": "ElevenLabs: 200 $ für TikTok-Vertonung",
"key_earn_notion": "Notion AI: 35 $ für Referate",
"key_порівняння_інструментів": "Vergleich der KI-Tools",

"key_мінікурси_заголовок": "Mini-Kurse und nützliche Anleitungen",
"key_заробіток_ai": "Wie man mit KI Geld verdient?",
"key_відео_гайд": "Video-Anleitung (1 Min) oder Textbeschreibung",
"key_топ_5_ai": "Top 5 Verdienstmöglichkeiten mit KI für Einsteiger",
"key_читати": "lesen",
"key_ai_шахрайство": "Wie vermeide ich Betrug bei der Arbeit mit KI?",
"key_faq": "FAQ",
"key_перший_клієнт": "Erster Freelance-Auftrag: Wie finde ich Kunden?",
"key_короткий_курс": "Kurz-Kurs",
"key_старт_без_знань": "Start ohne Vorkenntnisse: Website/Logo in 5 Minuten erstellen",
"key_відео": "Video",
"key_продаж_ai": "Wie verkauft man KI-Arbeiten auf Etsy/Pinterest?",
"key_faq_заголовок": "📚 Häufige Fragen (FAQ)",
"key_faq_опис": "Schnelle Antworten auf die häufigsten Fragen",
"key_faq_q1": "Wie verdient man mit KI-Texten Geld?",
"key_faq_a1": "Nutze ChatGPT oder Notion AI für Artikel, SEO-Texte, Produktbeschreibungen und Freelance-Aufträge.",
"key_faq_q2": "Welche Risiken gibt es beim Urheberrecht mit KI-Texten?",
"key_faq_a2": "Kopiere keine Sätze wortwörtlich. Erstelle einzigartige Texte und nutze Plagiatsprüfungen.",
"key_faq_q3": "Wie kann man KI-Bilder monetarisieren?",
"key_faq_a3": "Erstelle Kunst mit Midjourney oder Leonardo.ai und verkaufe sie auf Etsy, Redbubble oder Instagram.",
"key_faq_q4": "Kann man als Anfänger mit KI-Videos Geld verdienen?",
"key_faq_a4": "Ja! Verwende ElevenLabs für Voiceover oder Runway für Videos, lade sie auf TikTok oder Shorts hoch.",
"key_faq_q5": "Wie vermeide ich Bans bei KI-Vertonung?",
"key_faq_a5": "Füge Kommentare oder Kontext hinzu, meide sensible Themen, verändere die Stimme oder kombiniere sie mit natürlicher.",
"top_users": "🏆 Top-Nutzer",
"key_інструмент": "Werkzeug:",
"key_платформа": "Plattform:",
"key_годин_тиждень": "Stunden/Aufträge pro Woche:",
"key_розрахувати": "📈 Berechnen",
"community_heading": "🤝 Frag die Community",
"community_description": "Hast du eine Frage oder möchtest deine Erfahrung teilen? Tritt unserer Telegram-Gruppe bei und tausche dich mit anderen Nutzern aus!",
"join_telegram": "🔗 Telegram beitreten",
"label_earnings": "Einnahmen",
"label_jobs": "Jobs",
"about_intro_1": "Ich, Artem, habe den <strong>AI-Tool-Katalog</strong> erstellt, um allen zu helfen, die besten Möglichkeiten zum Geldverdienen mit KI zu finden.",
"about_intro_2": "Mein Ziel ist es, Technologie für alle zugänglich zu machen. Hier findest du echte Erfolgsgeschichten, Tipps und Bewertungen für den Einstieg von Grund auf.",
"about_intro_3": "Projekt mit ❤️ im Jahr 2025 erstellt.",
"label_investment": "Investition",
"subscribe_pitch_1": "🔐 Möchtest du mehr echte KI-Fälle und profitable Strategien?",
"subscribe_pitch_2": "📩 Abonniere unseren exklusiven Digest – nur $1/Woche",
"subscribe_button": "🔔 Abonnieren",

"badge_top_earnings": "🔥 Top-Einnahmen",
"badge_no_investment": "💸 Keine Investition",
"badge_many_jobs": "💼 Viele Jobs",
"modal_add_tool_title": "KI-Tool hinzufügen",
"label_tool_name": "Tool-Name:",
"label_category": "Kategorie:",
"label_username": "Dein Nickname:",
"label_link": "Link:",
"label_description": "Beschreibung:",
"label_honeypot": "Wenn du ein Mensch bist — lasse dieses Feld leer:",
"button_submit": "Absenden",
"button_clear_form": "Formular löschen",
email_placeholder: "Deine E-Mail",
  "chatgpt_title": "ChatGPT — KI-Tool",
"chatgpt_tip": "Tipp:",
"chatgpt_tip_text": "Nutze ChatGPT zur Erstellung eines Portfolios, Lebenslaufs, Blogs oder SEO-Inhalts für Kunden auf Upwork oder Fiverr.",
"show_example": "Verdienstbeispiel anzeigen",
"example_title": "📌 Wie genau verdient man mit ChatGPT?",
"example_guide": "Kurzanleitung:",
"example_step1": "Registriere dich bei Fiverr oder Upwork.",
"example_step2": "Erstelle ein Profil und biete Schreibdienste an.",
"example_step3": "Erstelle Texte mit ChatGPT, verbessere sie und sende sie an Kunden.",
"example_step4": "Startpreis: 10 $ für 500 Wörter.",
"example_case": "Beispiel: Andreas, 24 Jahre, aus Berlin — verdiente in 2 Monaten 1200 $. Erster Monat: 400 $, zweiter: 800 $.",
"example_tool": "Tool: Kostenlose Version verfügbar, Pro — $20/Monat.",
"chatgpt_description": "ChatGPT ist einer der leistungsstärksten Textgeneratoren, der Artikel, E-Mails, Skripte, Code und vieles mehr schreiben kann.",
"category_text": "Text",
no_votes: "Noch keine Stimmen",
"rating_summary": "({votes} Stimmen, Durchschnitt: {avg})",
"back_to_catalog": "Zurück zum Katalog",
"login": "Anmelden",
"login_title": "Profilanmeldung",
"login_header": "Anmeldung",
"login_btn": "Anmelden",
rating_summary: "({votes} votes, average: {avg})",
no_votes: "No votes yet",
midjourney_title: "Midjourney",
midjourney_tip: "Tip:",
midjourney_tip_text: "Generate images for Pinterest, Etsy, or social media.",
show_example: "Show earning example",
example_title: "📌 How to earn with Midjourney?",
example_guide: "Quick guide:",
midjourney_step1: "Create an account on Midjourney via Discord.",
midjourney_step2: "Generate images for art, posters, products.",
midjourney_step3: "Upload them on Etsy, Redbubble, or sell as custom orders.",
midjourney_step4: "Additionally — sell through Telegram or Fiverr.",
midjourney_case: "Case: Kate, 20, from Lviv — creates art posters for Etsy and Instagram. Earned $380 in a month, including 6 Pinterest design orders.",
example_tool: "Tool: Paid subscription from $10/month. Free trial available.",
key_опис_leonardo: "Bildgenerator für Comics, Spiele und Kunst. Ideal für Konzeptdesigns und NFTs.",
key_опис_heygen: "Erstellt Avatar-Videos mit Stimme. Nützlich für Präsentationen, Kurse und Social Media.",
key_опис_copyai: "Erstellt Marketingtexte, E-Mails, SEO-Beschreibungen — ideal für Texter.",
label_name: "Name:",
contacts_titlee: "← Zurück zur Startseite",
    coming_soonn: "Demnächst verfügbar",
    coming_soon: "🚧 Abschnitt kommt bald! 🚧",
    coming_soon_desc: "Wir arbeiten an dieser Seite. Bald finden Sie hier nützliche Informationen.",
  label_message: "Nachricht:",
  send_btn: "Senden",
  consulting_help: "💼 Brauchst du Hilfe mit KI-Tools oder dem Start einer Website?",
    consulting_button: "✉️ Schreib mir auf dem Telegram-Server, ich antworte dir.",
key_опис_bluewillow: "KI-Bilderzeugung wie Midjourney. Gut für Design, Drucke und NFTs.",
key_опис_voicemod: "Echtzeit-Stimmenverzerrer. Nützlich für Streamer, Videos oder Spaß.",
key_опис_writesonic: "Erstellt SEO-Texte, Blogartikel und E-Mail-Kampagnen. Ideal für Marketer und Texter.",
key_опис_artbreeder: "KI-Bildverschmelzung und Gesichtserstellung. Ideal für Art Design, Porträts und Kreativität.",
key_опис_speechify: "Wandelt Text in natürliche Sprache um. Ideal zum Anhören von Artikeln, Büchern oder PDFs.",
    key_опис_quillbot: "Paraphrasiert Texte, vereinfacht Grammatik. Sehr nützlich für Studenten und SEO-Redakteure.",
    key_опис_canva: "Fügt KI-Funktionen zu Canva hinzu: Auto-Design, Bildgenerierung, Vorlagen — alles in einem.",
    key_опис_taskade: "KI für Checklisten, Notizen und Arbeitsbereiche — ideal für Teams und Studenten.",
    key_опис_teleport: "Erstellt komplette HTML-Webseiten aus einfacher Beschreibung. Gut für schnelle Projekte.",
    key_опис_lumen5: "Erstellt automatisch Videos aus Text. Perfekt für Social Media, Präsentationen, Werbung.",
    key_опис_jenni: "Assistent für akademisches Schreiben. Gibt Formulierungsvorschläge — ideal für Studenten.",
key_заголовок_кейсів: "💡 Erfolgsgeschichten mit KI",
key_кейс_molly: "👩‍🏫 <strong>Molly (USA)</strong> verdient über <strong>100.000 $/Monat</strong><br>Sie erstellt Online-Kurse mit <strong>ChatGPT</strong> und <strong>Notion AI</strong>.<br><a href='https://www.youtube.com/@MollyKeyser' class='earnings-btn' target='_blank' style='margin-top:10px; display:inline-block;'>🔗 Fall ansehen</a>",
key_кейс_jason: "👨‍💼 <strong>Jason Lee</strong> (157 Tsd. Abonnenten) zeigt KI-Strategien für passives Einkommen,<br>und behauptet bis zu <strong>1.046 $/Tag</strong> durch KI-Dropshipping, Print-on-Demand und Affiliate-Marketing zu verdienen.<br><a href='https://www.youtube.com/@jasonleefinance' class='earnings-btn' target='_blank' style='margin-top:10px; display:inline-block;'>🔗 Fall ansehen</a>",
key_кейс_ben: "🧠 <strong>Ben</strong> erstellte 2 KI‑Influencer und verdiente 250.000 $ in einem Jahr durch Marketing.",
key_кейс_amanda: "👩‍💻 <strong>Amanda (USA)</strong> verdient bis zu 8.000 $ in 3 Wochen, indem sie nachts KI‑Chatbots testet.",
key_кейс_iryna:  "👩‍🎨 <strong>Iryna</strong> erstellt Illustrationen mit Midjourney und verkauft digitale Poster auf Etsy — 370 $/Monat.",
key_кейс_taras: "💬 <strong>Taras</strong> nutzt ChatGPT, um Texte auf Fiverr zu schreiben — 25–50 $ pro Auftrag.",
key_кейс_leila: "🎥 <strong>Leila</strong> veröffentlicht kurze Videos über KI auf TikTok und verdient mit Affiliate-Links — 800 $/Monat.",
"chatgpt_slide_1": "🎯 \"Erstellte eine Landingpage in 30 Minuten mit ChatGPT\" — Freelancer aus Polen",
"chatgpt_slide_2": "💬 \"Ich schreibe E-Mail-Kampagnen mit KI\" — Content-Creator aus Kanada",
"chatgpt_slide_3": "📖 \"50+ Texte in einem Monat auf Fiverr verkauft\" — Texterin aus Odessa",
 contacts_info: "Wenn Sie Fragen oder Vorschläge haben, schreiben Sie uns:",
    telegram: "Telegram",
"tab_features": "🔧 Funktionen",
"tab_tips": "💡 Tipps",
"tab_examples": "📚 Beispiele",
"nav_home": "🏠 Startseite",
"nav_compare": "📊 Vergleichen",
"nav_calculator": "🧮 Rechner",
"nav_home": "Startseite",
"nav_about": "Über uns",
"nav_contacts": "Kontakt",
"nav_support": "☕ Projekt unterstützen",
"nav_add_tool": "➕ Hinzufügen",
nav_add_history: "Geschichten",
contact_title: "Kontakt — AI Tools Katalog",
    contact_description: "Kontaktiere uns bei Fragen oder wenn du ein Tool vorschlagen möchtest.",
    contact_back: "← Zurück zur Startseite",
    contact_heading: "Kontakt",
    contact_text: "💬 Vorschläge, Fragen oder Partnerschaften — wir freuen uns auf dich!",
    contacts_header: "Kontaktieren Sie uns",

  }
};

function setLang(lang) {
  localStorage.setItem("lang", lang);
  document.documentElement.lang = lang;
  applyLang(lang); // Твоя функція для перекладу текстів

  const btn = document.querySelector(".lang-btn");
  if (btn) {
    btn.innerHTML =
      lang === "en" ? "🌐 English ▼" :
      lang === "de" ? "🌐 Deutsch ▼" :
      "🌐 Українська ▼";
  }

  const menu = document.querySelector(".lang-options");
  if (menu) menu.style.display = "none";
}
window.setLang = setLang;




function applyLang(lang) {
  const titleTag = document.querySelector('title');
const descTag = document.querySelector('meta[name="description"]');
const ogTitle = document.querySelector('meta[property="og:title"]');
const ogDesc = document.querySelector('meta[property="og:description"]');

if (lang === 'en') {
  titleTag.textContent = "AI Tools Catalog for Earning Money";
  descTag.setAttribute("content", "Compare top AI tools like ChatGPT, Midjourney, and more. Start earning as a freelancer or creator.");
  ogTitle.setAttribute("content", "AI Tools for Making Money");
  ogDesc.setAttribute("content", "Real cases and best AI tools to help you earn online.");
} else if (lang === 'de') {
  titleTag.textContent = "KI-Tools zum Geldverdienen – Katalog";
  descTag.setAttribute("content", "Finde die besten KI-Tools wie ChatGPT, Midjourney und mehr. Verdiene online mit AI, egal ob Freelancer oder Anfänger.");
  ogTitle.setAttribute("content", "KI-Tools zum Geldverdienen");
  ogDesc.setAttribute("content", "Vergleiche Tools, sieh echte Erfolgsgeschichten und starte jetzt dein KI-Einkommen.");
} else {
  titleTag.textContent = "Каталог AI-Інструментів для Заробітку";
  descTag.setAttribute("content", "Порівнюй найкращі AI-інструменти — для фрілансу, бізнесу, Etsy або TikTok.");
  ogTitle.setAttribute("content", "Каталог AI-Інструментів для Заробітку");
  ogDesc.setAttribute("content", "Порівнюй, дізнавайся кейси та розраховуй прибуток. Всі AI-інструменти в одному місці!");
}

  const elements = document.querySelectorAll('[data-i18n]');
  elements.forEach(el => {
    const key = el.getAttribute('data-i18n');
    const translation = translations[lang] && translations[lang][key];
    if (translation) {
      el.innerHTML = translation;
    }
  });
}


window.translations = translations;
window.setLang = setLang;
window.applyLang = applyLang;

console.log("🌐 Встановлено мову через setLang:", localStorage.getItem("lang"));

if (window.location.search === "?") {
  history.replaceState(null, "", window.location.pathname);
}
